/**
 * AUTO-GENERATED by scripts/gen-trivia.ts from openfootball World Cup history.
 * Do NOT edit by hand — re-run `npm run trivia:gen`. Penalty-aware winner
 * resolution; 1950 (round-robin) is handled by the curated bank instead.
 */
import type { TriviaQuestion } from "./questions";

export const GENERATED_QUESTIONS: TriviaQuestion[] = [
  {
    "id": "g_1930_w",
    "q": "Who won the 1930 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Czechoslovakia"
    ],
    "answerIndex": 0,
    "category": "Winners"
  },
  {
    "id": "g_1930_r",
    "q": "Which country did Uruguay beat in the 1930 World Cup Final?",
    "choices": [
      "Uruguay",
      "Italy",
      "Czechoslovakia",
      "Argentina"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1930_s",
    "q": "What was the final score of the 1930 World Cup Final?",
    "choices": [
      "4-2",
      "1-0",
      "2-1",
      "3-1"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1930_c",
    "q": "In which city was the 1930 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Paris",
      "Bern"
    ],
    "answerIndex": 0,
    "category": "Venues"
  },
  {
    "id": "g_1930_scorer",
    "q": "Who scored for Uruguay in the 1930 World Cup Final?",
    "choices": [
      "Cea",
      "Dorado",
      "Iriarte",
      "Castro"
    ],
    "answerIndex": 1,
    "category": "Players"
  },
  {
    "id": "g_1934_w",
    "q": "Who won the 1934 FIFA World Cup?",
    "choices": [
      "Italy",
      "Uruguay",
      "Argentina",
      "Czechoslovakia"
    ],
    "answerIndex": 0,
    "category": "Winners"
  },
  {
    "id": "g_1934_r",
    "q": "Which country did Italy beat in the 1934 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Czechoslovakia"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1934_s",
    "q": "What was the final score of the 1934 World Cup Final?",
    "choices": [
      "2-1",
      "1-0",
      "3-1",
      "2-0"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1934_c",
    "q": "In which city was the 1934 World Cup Final played?",
    "choices": [
      "Rome",
      "Montevideo",
      "Paris",
      "Bern"
    ],
    "answerIndex": 0,
    "category": "Venues"
  },
  {
    "id": "g_1934_scorer",
    "q": "Who scored for Italy in the 1934 World Cup Final?",
    "choices": [
      "Dorado",
      "Orsi",
      "Cea",
      "Iriarte"
    ],
    "answerIndex": 1,
    "category": "Players"
  },
  {
    "id": "g_1938_w",
    "q": "Who won the 1938 FIFA World Cup?",
    "choices": [
      "Italy",
      "Uruguay",
      "Argentina",
      "Czechoslovakia"
    ],
    "answerIndex": 0,
    "category": "Winners"
  },
  {
    "id": "g_1938_r",
    "q": "Which country did Italy beat in the 1938 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Hungary"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1938_s",
    "q": "What was the final score of the 1938 World Cup Final?",
    "choices": [
      "4-2",
      "1-0",
      "2-1",
      "3-1"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1938_c",
    "q": "In which city was the 1938 World Cup Final played?",
    "choices": [
      "Paris",
      "Montevideo",
      "Rome",
      "Bern"
    ],
    "answerIndex": 0,
    "category": "Venues"
  },
  {
    "id": "g_1938_scorer",
    "q": "Who scored for Italy in the 1938 World Cup Final?",
    "choices": [
      "Dorado",
      "Colaussi",
      "Cea",
      "Iriarte"
    ],
    "answerIndex": 1,
    "category": "Players"
  },
  {
    "id": "g_1954_w",
    "q": "Who won the 1954 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "West Germany",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_1954_r",
    "q": "Which country did West Germany beat in the 1954 World Cup Final?",
    "choices": [
      "Uruguay",
      "Hungary",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1954_s",
    "q": "What was the final score of the 1954 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "3-2",
      "3-1"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_1954_c",
    "q": "In which city was the 1954 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Bern",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_1958_w",
    "q": "Who won the 1958 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Brazil",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_1958_r",
    "q": "Which country did Brazil beat in the 1958 World Cup Final?",
    "choices": [
      "Uruguay",
      "Sweden",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1958_s",
    "q": "What was the final score of the 1958 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "5-2",
      "3-1"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_1958_c",
    "q": "In which city was the 1958 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Solna",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_1962_w",
    "q": "Who won the 1962 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Brazil",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Winners"
  },
  {
    "id": "g_1962_r",
    "q": "Which country did Brazil beat in the 1962 World Cup Final?",
    "choices": [
      "Czechoslovakia",
      "Uruguay",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1962_s",
    "q": "What was the final score of the 1962 World Cup Final?",
    "choices": [
      "1-0",
      "3-1",
      "2-1",
      "2-0"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1962_c",
    "q": "In which city was the 1962 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Santiago",
      "Rome",
      "Paris"
    ],
    "answerIndex": 1,
    "category": "Venues"
  },
  {
    "id": "g_1966_w",
    "q": "Who won the 1966 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "England",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Winners"
  },
  {
    "id": "g_1966_r",
    "q": "Which country did England beat in the 1966 World Cup Final?",
    "choices": [
      "West Germany",
      "Uruguay",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1966_s",
    "q": "What was the final score of the 1966 World Cup Final?",
    "choices": [
      "1-0",
      "4-2",
      "2-1",
      "3-1"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1966_c",
    "q": "In which city was the 1966 World Cup Final played?",
    "choices": [
      "Montevideo",
      "London",
      "Rome",
      "Paris"
    ],
    "answerIndex": 1,
    "category": "Venues"
  },
  {
    "id": "g_1970_w",
    "q": "Who won the 1970 FIFA World Cup?",
    "choices": [
      "Brazil",
      "Uruguay",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 0,
    "category": "Winners"
  },
  {
    "id": "g_1970_r",
    "q": "Which country did Brazil beat in the 1970 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Czechoslovakia",
      "Italy"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1970_s",
    "q": "What was the final score of the 1970 World Cup Final?",
    "choices": [
      "4-1",
      "1-0",
      "2-1",
      "3-1"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1970_c",
    "q": "In which city was the 1970 World Cup Final played?",
    "choices": [
      "Mexico City",
      "Montevideo",
      "Rome",
      "Paris"
    ],
    "answerIndex": 0,
    "category": "Venues"
  },
  {
    "id": "g_1974_w",
    "q": "Who won the 1974 FIFA World Cup?",
    "choices": [
      "West Germany",
      "Uruguay",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 0,
    "category": "Winners"
  },
  {
    "id": "g_1974_r",
    "q": "Which country did West Germany beat in the 1974 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Netherlands"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1974_s",
    "q": "What was the final score of the 1974 World Cup Final?",
    "choices": [
      "2-1",
      "1-0",
      "3-1",
      "2-0"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1974_c",
    "q": "In which city was the 1974 World Cup Final played?",
    "choices": [
      "München",
      "Montevideo",
      "Rome",
      "Paris"
    ],
    "answerIndex": 0,
    "category": "Venues"
  },
  {
    "id": "g_1978_w",
    "q": "Who won the 1978 FIFA World Cup?",
    "choices": [
      "Argentina",
      "Uruguay",
      "Italy",
      "Czechoslovakia"
    ],
    "answerIndex": 0,
    "category": "Winners"
  },
  {
    "id": "g_1978_r",
    "q": "Which country did Argentina beat in the 1978 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Netherlands"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1978_s",
    "q": "What was the final score of the 1978 World Cup Final?",
    "choices": [
      "3-1",
      "1-0",
      "2-1",
      "2-0"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_1978_c",
    "q": "In which city was the 1978 World Cup Final played?",
    "choices": [
      "Buenos Aires",
      "Montevideo",
      "Rome",
      "Paris"
    ],
    "answerIndex": 0,
    "category": "Venues"
  },
  {
    "id": "g_1982_w",
    "q": "Who won the 1982 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Czechoslovakia",
      "Italy"
    ],
    "answerIndex": 3,
    "category": "Winners"
  },
  {
    "id": "g_1982_r",
    "q": "Which country did Italy beat in the 1982 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "West Germany",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_1982_s",
    "q": "What was the final score of the 1982 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "2-0",
      "3-1"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1982_c",
    "q": "In which city was the 1982 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Paris",
      "Estadio Santiago Bernabéu"
    ],
    "answerIndex": 3,
    "category": "Venues"
  },
  {
    "id": "g_1986_w",
    "q": "Who won the 1986 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Italy",
      "Czechoslovakia",
      "Argentina"
    ],
    "answerIndex": 3,
    "category": "Winners"
  },
  {
    "id": "g_1986_r",
    "q": "Which country did Argentina beat in the 1986 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "West Germany",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_1986_s",
    "q": "What was the final score of the 1986 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "3-1",
      "3-2"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_1986_c",
    "q": "In which city was the 1986 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Paris",
      "Mexico City"
    ],
    "answerIndex": 3,
    "category": "Venues"
  },
  {
    "id": "g_1990_w",
    "q": "Who won the 1990 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "West Germany",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_1990_r",
    "q": "Which country did West Germany beat in the 1990 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Czechoslovakia"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1990_s",
    "q": "What was the final score of the 1990 World Cup Final?",
    "choices": [
      "2-1",
      "3-1",
      "1-0",
      "2-0"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_1990_c",
    "q": "In which city was the 1990 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Paris",
      "Rome",
      "Bern"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_1990_scorer",
    "q": "Who scored for West Germany in the 1990 World Cup Final?",
    "choices": [
      "Dorado",
      "Cea",
      "Iriarte",
      "Brehme"
    ],
    "answerIndex": 3,
    "category": "Players"
  },
  {
    "id": "g_1994_w",
    "q": "Who won the 1994 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Brazil",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_1994_r",
    "q": "Which country did Brazil beat in the 1994 World Cup Final?",
    "choices": [
      "Uruguay",
      "Italy",
      "Argentina",
      "Czechoslovakia"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1994_pen",
    "q": "How was the 1994 World Cup Final decided (it finished 0-0)?",
    "choices": [
      "Golden goal",
      "Penalty shootout",
      "Replay",
      "Coin toss"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1994_c",
    "q": "In which city was the 1994 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Pasadena",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_1998_w",
    "q": "Who won the 1998 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "France",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_1998_r",
    "q": "Which country did France beat in the 1998 World Cup Final?",
    "choices": [
      "Uruguay",
      "Brazil",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_1998_s",
    "q": "What was the final score of the 1998 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "3-0",
      "3-1"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_1998_c",
    "q": "In which city was the 1998 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Saint-Denis",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_2002_w",
    "q": "Who won the 2002 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Brazil"
    ],
    "answerIndex": 3,
    "category": "Winners"
  },
  {
    "id": "g_2002_r",
    "q": "Which country did Brazil beat in the 2002 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Germany",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_2002_s",
    "q": "What was the final score of the 2002 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "3-1",
      "2-0"
    ],
    "answerIndex": 3,
    "category": "Finals"
  },
  {
    "id": "g_2002_c",
    "q": "In which city was the 2002 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Paris",
      "Yokohama"
    ],
    "answerIndex": 3,
    "category": "Venues"
  },
  {
    "id": "g_2006_w",
    "q": "Who won the 2006 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Czechoslovakia",
      "Italy"
    ],
    "answerIndex": 3,
    "category": "Winners"
  },
  {
    "id": "g_2006_r",
    "q": "Which country did Italy beat in the 2006 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "France",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_2006_pen",
    "q": "How was the 2006 World Cup Final decided (it finished 1-1)?",
    "choices": [
      "Golden goal",
      "Penalty shootout",
      "Replay",
      "Coin toss"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_2006_c",
    "q": "In which city was the 2006 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Paris",
      "Berlin"
    ],
    "answerIndex": 3,
    "category": "Venues"
  },
  {
    "id": "g_2006_scorer",
    "q": "Who scored for Italy in the 2006 World Cup Final?",
    "choices": [
      "Materazzi",
      "Dorado",
      "Cea",
      "Iriarte"
    ],
    "answerIndex": 0,
    "category": "Players"
  },
  {
    "id": "g_2010_w",
    "q": "Who won the 2010 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Spain",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_2010_r",
    "q": "Which country did Spain beat in the 2010 World Cup Final?",
    "choices": [
      "Uruguay",
      "Netherlands",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_2010_s",
    "q": "What was the final score of the 2010 World Cup Final?",
    "choices": [
      "2-1",
      "3-1",
      "1-0",
      "2-0"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_2010_c",
    "q": "In which city was the 2010 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Johannesburg",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_2014_w",
    "q": "Who won the 2014 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Germany",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_2014_r",
    "q": "Which country did Germany beat in the 2014 World Cup Final?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Czechoslovakia"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_2014_s",
    "q": "What was the final score of the 2014 World Cup Final?",
    "choices": [
      "2-1",
      "3-1",
      "1-0",
      "2-0"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_2014_c",
    "q": "In which city was the 2014 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Rio de Janeiro",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_2014_scorer",
    "q": "Who scored for Germany in the 2014 World Cup Final?",
    "choices": [
      "Dorado",
      "Cea",
      "Iriarte",
      "Mario Götze"
    ],
    "answerIndex": 3,
    "category": "Players"
  },
  {
    "id": "g_2018_w",
    "q": "Who won the 2018 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "France",
      "Italy"
    ],
    "answerIndex": 2,
    "category": "Winners"
  },
  {
    "id": "g_2018_r",
    "q": "Which country did France beat in the 2018 World Cup Final?",
    "choices": [
      "Uruguay",
      "Croatia",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_2018_s",
    "q": "What was the final score of the 2018 World Cup Final?",
    "choices": [
      "1-0",
      "2-1",
      "4-2",
      "3-1"
    ],
    "answerIndex": 2,
    "category": "Finals"
  },
  {
    "id": "g_2018_c",
    "q": "In which city was the 2018 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Rome",
      "Moscow",
      "Paris"
    ],
    "answerIndex": 2,
    "category": "Venues"
  },
  {
    "id": "g_2018_scorer",
    "q": "Who scored for France in the 2018 World Cup Final?",
    "choices": [
      "Dorado",
      "Cea",
      "Iriarte",
      "Mandžukić"
    ],
    "answerIndex": 3,
    "category": "Players"
  },
  {
    "id": "g_2022_w",
    "q": "Who won the 2022 FIFA World Cup?",
    "choices": [
      "Uruguay",
      "Argentina",
      "Italy",
      "Czechoslovakia"
    ],
    "answerIndex": 1,
    "category": "Winners"
  },
  {
    "id": "g_2022_r",
    "q": "Which country did Argentina beat in the 2022 World Cup Final?",
    "choices": [
      "France",
      "Uruguay",
      "Argentina",
      "Italy"
    ],
    "answerIndex": 0,
    "category": "Finals"
  },
  {
    "id": "g_2022_pen",
    "q": "How was the 2022 World Cup Final decided (it finished 2-2)?",
    "choices": [
      "Golden goal",
      "Penalty shootout",
      "Replay",
      "Coin toss"
    ],
    "answerIndex": 1,
    "category": "Finals"
  },
  {
    "id": "g_2022_c",
    "q": "In which city was the 2022 World Cup Final played?",
    "choices": [
      "Montevideo",
      "Lusail",
      "Rome",
      "Paris"
    ],
    "answerIndex": 1,
    "category": "Venues"
  },
  {
    "id": "g_2022_scorer",
    "q": "Who scored for Argentina in the 2022 World Cup Final?",
    "choices": [
      "Dorado",
      "Cea",
      "Lionel Messi",
      "Iriarte"
    ],
    "answerIndex": 2,
    "category": "Players"
  }
];
